# Generated by Django 2.1.6 on 2019-02-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=30)),
                ('participant_phone', models.CharField(max_length=30)),
                ('participant_email', models.CharField(max_length=30)),
            ],
        ),
    ]
