# Generated by Django 2.1.6 on 2019-02-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_payment',
            field=models.BooleanField(default=False),
        ),
    ]
