# Generated by Django 2.1.6 on 2019-02-11 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('participant_manager', '0002_participant_participant_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_essay',
            field=models.TextField(default=datetime.datetime(2019, 2, 11, 13, 43, 31, 831852, tzinfo=utc), max_length=3000),
            preserve_default=False,
        ),
    ]
