# Generated by Django 2.1.5 on 2019-02-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_manager', '0003_participant_participant_essay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_email',
            field=models.EmailField(max_length=254),
        ),
    ]
